# Generated by Django 5.0.7 on 2024-07-15 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='grupos.grupos'),
        ),
        migrations.AddField(
            model_name='carta',
            name='carta_par',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pareja', to='games.carta'),
        ),
        migrations.AddField(
            model_name='memorama',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorama', to='games.asignacionactividad'),
        ),
        migrations.AddField(
            model_name='carta',
            name='memorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='games.memorama'),
        ),
        migrations.AddField(
            model_name='puntajes',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='games.asignacionactividad'),
        ),
    ]
