# Generated by Django 5.0.7 on 2024-07-15 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puntajes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizz',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='games.asignacionactividad'),
        ),
        migrations.AddField(
            model_name='reactivos',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivos', to='games.quizz'),
        ),
    ]
